postfix: metric_learning

seed: 42
precision: 16
accelerator: gpu
devices: 1
find_unused_parameters: False

dataframe_name: df.csv
dataset_root: data/
logs_root: logs/
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

num_workers: 10
cache_size: 0

transforms_train:
  name: augs_hypvit_torch
  args:
    im_size: 224

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

sampler:
  name: balance
  args:
    n_labels: 80
    n_instances: 9

bs_val: 256
max_epochs: 300
valid_period: 1

metric_args:
  metrics_to_exclude_from_visualization: [cmc]
  cmc_top_k: [1]
  map_top_k: [5]
  fmr_vals: []
  pcf_variance: [0.5, 0.9, 0.99]
  return_only_overall_category: True
  visualize_only_overall_category: True

log_images: False

metric_for_checkpointing: OVERALL/cmc/1

extractor:
  name: vit
  args:
    normalise_features: True
    use_multi_scale: False
    weights: vits16_dino
    arch: vits16

criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: 0.2
    reduction: mean
    miner:
      name: hard_triplets
      args: {}

optimizer:
  name: adam
  args:
    lr: 1e-5

scheduling: null

# logger:
#   name: mlflow
#   args:
#     experiment_name: "vit_dino"
#     tracking_uri: "http://mlf-s-001.kifr-ru.local:8000"

hydra_dir: ${logs_root}/${logs_folder}/

tags:
  - ${postfix}
  - vit_dino

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
    - pkg://oml.configs
  job:
    chdir: True
